version: '3.5'

services:
  webnsurf-nestjs-postgresql:
    container_name: webnsurf-nestjs-dev_DB
    build: pipelines/postgresql
    image: webnsurf-nestjs-postgresql:latest
    ports:
      - 5432:5432
    env_file: .env

  webnsurf-nestjs-dev-api:
    container_name: webnsurf-nestjs-dev_BE
    build:
      context: .
      dockerfile: pipelines/Dockerfile.dev
    image: webnsurf-nestjs-dev-api:latest
    ports:
      - ${PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.webnsurf-nestjs-dev-api-redirect.rule: Host(`nestjs.dev.webnsurf.com`) && PathPrefix(`/api`)
      traefik.http.routers.webnsurf-nestjs-dev-api-redirect.middlewares: https-redirect@file
      traefik.http.routers.webnsurf-nestjs-dev-api-redirect.entrypoints: web

      traefik.http.routers.webnsurf-nestjs-dev-api.rule: Host(`nestjs.dev.webnsurf.com`) && PathPrefix(`/api`)
      traefik.http.routers.webnsurf-nestjs-dev-api.entrypoints: websecure
      traefik.http.routers.webnsurf-nestjs-dev-api.tls: true
    volumes:
      - /app/dist
      - /app/node_modules
      - $PWD:/app
      - $PWD/.env:/app/.env
    env_file: .env
    environment:
      NODE_ENV: development
      RUNTIME_ENV: development

networks:
  default:
    external:
      name: webnsurf_network
