version: '3.5'

services:
  webnsurf-nestjs-postgresql:
    container_name: ${STACK}-dev_DB
    build: pipelines/postgresql
    image: ${STACK}-postgresql:latest
    ports:
      - 5432:5432
    env_file: .env

  webnsurf-nestjs-api-dev:
    container_name: ${STACK}-dev_BE
    build:
      context: .
      dockerfile: pipelines/Dockerfile.dev
    image: ${IMAGE}-dev:latest
    ports:
      - ${PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.webnsurf-nestjs-api-dev-redirect.rule: Host(`${DEV_URL}`) && PathPrefix(`/api`)
      traefik.http.routers.webnsurf-nestjs-api-dev-redirect.middlewares: https-redirect@file
      traefik.http.routers.webnsurf-nestjs-api-dev-redirect.entrypoints: web

      traefik.http.routers.webnsurf-nestjs-api-dev.rule: Host(`${DEV_URL}`) && PathPrefix(`/api`)
      traefik.http.routers.webnsurf-nestjs-api-dev.entrypoints: websecure
      traefik.http.routers.webnsurf-nestjs-api-dev.tls: true
    volumes:
      - /app/dist
      - /app/node_modules
      - $PWD:/app
      - $PWD/.env:/app/.env
    env_file: .env
    environment:
      NODE_ENV: development
      RUNTIME_ENV: development

networks:
  default:
    external:
      name: webnsurf_network
