version: '3.5'

services:
  webnsurf-nestjs-api:
    container_name: ${NAME}
    image: ${IMAGE}:${TAG}
    tty: true
    ports:
      - ${PORT}
    labels:
      traefik.enable: true
      traefik.http.routers.webnsurf-nestjs-api-redirect.rule: Host(`${URL}`) && PathPrefix(`/api`)
      traefik.http.routers.webnsurf-nestjs-api-redirect.entrypoints: web
      traefik.http.routers.webnsurf-nestjs-api-redirect.middlewares: https-redirect@file

      traefik.http.routers.webnsurf-nestjs-api.rule: Host(`${URL}`) && PathPrefix(`/api`)
      traefik.http.routers.webnsurf-nestjs-api.entrypoints: websecure
      traefik.http.routers.webnsurf-nestjs-api.tls: true
    env_file: ${ENV_FILE}

networks:
  default:
    external:
      name: webnsurf_network
